# Build da aplicação
FROM node:20-alpine AS build

WORKDIR /app

COPY package*.json ./
RUN npm install
COPY . .

# Build de produção do Vue (Vite)
RUN npm run build

# Servir com Nginx
FROM nginx:alpine

# Remove configuração default
RUN rm /etc/nginx/conf.d/default.conf

# Copia arquivo de configuração customizada
COPY nginx.conf /etc/nginx/conf.d

# Copia build para Nginx
COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 8001

CMD ["nginx", "-g", "daemon off;"]
