# imagem base Node para desenvolvimento
FROM node:20-alpine

WORKDIR /app

# Copia package.json e package-lock.json
COPY package*.json ./

# Instala dependências
RUN npm install

# Copia código
COPY . .

# Expõe porta do Vite
EXPOSE 5173

# Comando para rodar em dev
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
