export const countries = [
  { label: "Afeganistão", value: "AF" },
  { label: "África do Sul", value: "ZA" },
  { label: "Albânia", value: "AL" },
  { label: "Alemanha", value: "DE" },
  { label: "Andorra", value: "AD" },
  { label: "Angola", value: "AO" },
  { label: "Antígua e Barbuda", value: "AG" },
  { label: "Arábia Saudita", value: "SA" },
  { label: "Argélia", value: "DZ" },
  { label: "Argentina", value: "AR" },
  { label: "Armênia", value: "AM" },
  { label: "Austrália", value: "AU" },
  { label: "Áustria", value: "AT" },
  { label: "Azerbaijão", value: "AZ" },
  { label: "Bahamas", value: "BS" },
  { label: "Bangladesh", value: "BD" },
  { label: "Barbados", value: "BB" },
  { label: "Barein", value: "BH" },
  { label: "Bélgica", value: "BE" },
  { label: "Belize", value: "BZ" },
  { label: "Benim", value: "BJ" },
  { label: "Bielorrússia", value: "BY" },
  { label: "Bolívia", value: "BO" },
  { label: "Bósnia e Herzegovina", value: "BA" },
  { label: "Botswana", value: "BW" },
  { label: "Brasil", value: "BR" },
  { label: "Brunei", value: "BN" },
  { label: "Bulgária", value: "BG" },
  { label: "Burkina Faso", value: "BF" },
  { label: "Burundi", value: "BI" },
  { label: "Butão", value: "BT" },
  { label: "Cabo Verde", value: "CV" },
  { label: "Camarões", value: "CM" },
  { label: "Camboja", value: "KH" },
  { label: "Canadá", value: "CA" },
  { label: "Catar", value: "QA" },
  { label: "Cazaquistão", value: "KZ" },
  { label: "Chade", value: "TD" },
  { label: "Chile", value: "CL" },
  { label: "China", value: "CN" },
  { label: "Chipre", value: "CY" },
  { label: "Colômbia", value: "CO" },
  { label: "Comores", value: "KM" },
  { label: "Congo", value: "CG" },
  { label: "Coreia do Norte", value: "KP" },
  { label: "Coreia do Sul", value: "KR" },
  { label: "Costa do Marfim", value: "CI" },
  { label: "Costa Rica", value: "CR" },
  { label: "Croácia", value: "HR" },
  { label: "Cuba", value: "CU" },
  { label: "Dinamarca", value: "DK" },
  { label: "Djibouti", value: "DJ" },
  { label: "Dominica", value: "DM" },
  { label: "Egito", value: "EG" },
  { label: "El Salvador", value: "SV" },
  { label: "Emirados Árabes Unidos", value: "AE" },
  { label: "Equador", value: "EC" },
  { label: "Eritreia", value: "ER" },
  { label: "Eslováquia", value: "SK" },
  { label: "Eslovênia", value: "SI" },
  { label: "Espanha", value: "ES" },
  { label: "Estados Unidos", value: "US" },
  { label: "Estônia", value: "EE" },
  { label: "Eswatini", value: "SZ" },
  { label: "Etiópia", value: "ET" },
  { label: "Fiji", value: "FJ" },
  { label: "Filipinas", value: "PH" },
  { label: "Finlândia", value: "FI" },
  { label: "França", value: "FR" },
  { label: "Gabão", value: "GA" },
  { label: "Gâmbia", value: "GM" },
  { label: "Gana", value: "GH" },
  { label: "Geórgia", value: "GE" },
  { label: "Grécia", value: "GR" },
  { label: "Granada", value: "GD" },
  { label: "Guatemala", value: "GT" },
  { label: "Guiana", value: "GY" },
  { label: "Guiné", value: "GN" },
  { label: "Guiné Equatorial", value: "GQ" },
  { label: "Guiné-Bissau", value: "GW" },
  { label: "Haiti", value: "HT" },
  { label: "Holanda", value: "NL" },
  { label: "Honduras", value: "HN" },
  { label: "Hungria", value: "HU" },
  { label: "Iêmen", value: "YE" },
  { label: "Ilhas Maldivas", value: "MV" },
  { label: "Ilhas Marshall", value: "MH" },
  { label: "Ilhas Maurício", value: "MU" },
  { label: "Ilhas Salomão", value: "SB" },
  { label: "Índia", value: "IN" },
  { label: "Indonésia", value: "ID" },
  { label: "Irã", value: "IR" },
  { label: "Iraque", value: "IQ" },
  { label: "Irlanda", value: "IE" },
  { label: "Islândia", value: "IS" },
  { label: "Israel", value: "IL" },
  { label: "Itália", value: "IT" },
  { label: "Jamaica", value: "JM" },
  { label: "Japão", value: "JP" },
  { label: "Jordânia", value: "JO" },
  { label: "Kosovo", value: "XK" },
  { label: "Kuwait", value: "KW" },
  { label: "Laos", value: "LA" },
  { label: "Lesoto", value: "LS" },
  { label: "Letônia", value: "LV" },
  { label: "Líbano", value: "LB" },
  { label: "Libéria", value: "LR" },
  { label: "Líbia", value: "LY" },
  { label: "Liechtenstein", value: "LI" },
  { label: "Lituânia", value: "LT" },
  { label: "Luxemburgo", value: "LU" },
  { label: "Macedônia do Norte", value: "MK" },
  { label: "Madagascar", value: "MG" },
  { label: "Malásia", value: "MY" },
  { label: "Malawi", value: "MW" },
  { label: "Mali", value: "ML" },
  { label: "Malta", value: "MT" },
  { label: "Marrocos", value: "MA" },
  { label: "México", value: "MX" },
  { label: "Moçambique", value: "MZ" },
  { label: "Moldávia", value: "MD" },
  { label: "Mônaco", value: "MC" },
  { label: "Mongólia", value: "MN" },
  { label: "Montenegro", value: "ME" },
  { label: "Namíbia", value: "NA" },
  { label: "Nepal", value: "NP" },
  { label: "Nicarágua", value: "NI" },
  { label: "Níger", value: "NE" },
  { label: "Nigéria", value: "NG" },
  { label: "Noruega", value: "NO" },
  { label: "Nova Zelândia", value: "NZ" },
  { label: "Omã", value: "OM" },
  { label: "Panamá", value: "PA" },
  { label: "Papua-Nova Guiné", value: "PG" },
  { label: "Paquistão", value: "PK" },
  { label: "Paraguai", value: "PY" },
  { label: "Peru", value: "PE" },
  { label: "Polônia", value: "PL" },
  { label: "Portugal", value: "PT" },
  { label: "Quênia", value: "KE" },
  { label: "Quirguistão", value: "KG" },
  { label: "Reino Unido", value: "GB" },
  { label: "República Centro-Africana", value: "CF" },
  { label: "República Democrática do Congo", value: "CD" },
  { label: "República Dominicana", value: "DO" },
  { label: "República Tcheca", value: "CZ" },
  { label: "Romênia", value: "RO" },
  { label: "Ruanda", value: "RW" },
  { label: "Rússia", value: "RU" },
  { label: "São Cristóvão e Névis", value: "KN" },
  { label: "São Marinho", value: "SM" },
  { label: "São Tomé e Príncipe", value: "ST" },
  { label: "São Vicente e Granadinas", value: "VC" },
  { label: "Senegal", value: "SN" },
  { label: "Sérvia", value: "RS" },
  { label: "Síria", value: "SY" },
  { label: "Somália", value: "SO" },
  { label: "Sri Lanka", value: "LK" },
  { label: "Sudão", value: "SD" },
  { label: "Sudão do Sul", value: "SS" },
  { label: "Suécia", value: "SE" },
  { label: "Suíça", value: "CH" },
  { label: "Suriname", value: "SR" },
  { label: "Tailândia", value: "TH" },
  { label: "Taiwan", value: "TW" },
  { label: "Tanzânia", value: "TZ" },
  { label: "Togo", value: "TG" },
  { label: "Trinidad e Tobago", value: "TT" },
  { label: "Tunísia", value: "TN" },
  { label: "Turcomenistão", value: "TM" },
  { label: "Turquia", value: "TR" },
  { label: "Ucrânia", value: "UA" },
  { label: "Uganda", value: "UG" },
  { label: "Uruguai", value: "UY" },
  { label: "Uzbequistão", value: "UZ" },
  { label: "Vaticano", value: "VA" },
  { label: "Venezuela", value: "VE" },
  { label: "Vietnã", value: "VN" },
  { label: "Zâmbia", value: "ZM" },
  { label: "Zimbábue", value: "ZW" }
]
